export enum BotCallbackAction {
  ACTION_BUY_GAS = 'ACTION_BUY_GAS',
  ACTION_MY_ORDERS = 'ACTION_MY_ORDERS',
  ACTION_HELP = 'ACTION_HELP',
  ACTION_BACK = 'ACTION_BACK',
  ACTION_HOME = 'ACTION_HOME',
  ACTION_PAY_NOW = 'ACTION_PAY_NOW',
  ACTION_CANCEL_ORDER = 'ACTION_CANCEL_ORDER',
  ACTION_SELL_CRYPTO = 'ACTION_SELL_CRYPTO',
  ACTION_BANK = 'ACTION_BANK',
  ACTION_WALLET = 'ACTION_WALLET',
  ACTION_WITHDRAW = 'ACTION_WITHDRAW',
}

export enum BotCallbackChain {
  CHAIN_SOLANA = 'CHAIN_SOLANA',
  CHAIN_BASE = 'CHAIN_BASE',
  CHAIN_TON = 'CHAIN_TON',
}

export enum BotCallbackAmount {
  AMT_1000 = 'AMT_1000',
  AMT_2500 = 'AMT_2500',
  AMT_5000 = 'AMT_5000',
  AMT_CUSTOM = 'AMT_CUSTOM',
}

export enum BotCallbackCryptoAsset {
  CRYPTO_USDT = 'CRYPTO_USDT',
  // Temporarily disabled - USDT only for off-ramp
  // CRYPTO_TON = 'CRYPTO_TON',
  // CRYPTO_SOL = 'CRYPTO_SOL',
}

export enum BotCallbackPayoutDestination {
  PAYOUT_INTERNAL_WALLET = 'PAYOUT_INTERNAL_WALLET',
  PAYOUT_SAVED_BANK = 'PAYOUT_SAVED_BANK',
}

export enum BotCallbackBank {
  BANK_SELECT = 'BANK_SELECT',
}

export enum BotSessionStep {
  IDLE = 'IDLE',
  SELECT_CHAIN = 'SELECT_CHAIN',
  SELECT_AMOUNT = 'SELECT_AMOUNT',
  AWAITING_CUSTOM_AMOUNT = 'AWAITING_CUSTOM_AMOUNT',
  AWAITING_WALLET = 'AWAITING_WALLET',
  AWAITING_SELL_AMOUNT = 'AWAITING_SELL_AMOUNT',
  AWAITING_SELL_TX_ID = 'AWAITING_SELL_TX_ID',
  AWAITING_SELL_PAYOUT_CHOICE = 'AWAITING_SELL_PAYOUT_CHOICE',
  AWAITING_SELL_BANK_CHOICE = 'AWAITING_SELL_BANK_CHOICE',
  AWAITING_BANK_SELECTION = 'AWAITING_BANK_SELECTION',
  AWAITING_ACCOUNT_NUMBER = 'AWAITING_ACCOUNT_NUMBER',
  AWAITING_WITHDRAWAL_AMOUNT = 'AWAITING_WITHDRAWAL_AMOUNT',
  AWAITING_WITHDRAWAL_BANK = 'AWAITING_WITHDRAWAL_BANK',
}

export const AMOUNT_NAIRA_MAP: Partial<Record<BotCallbackAmount, number>> = {
  [BotCallbackAmount.AMT_1000]: 1000,
  [BotCallbackAmount.AMT_2500]: 2500,
  [BotCallbackAmount.AMT_5000]: 5000,
};

export const CHAIN_DISPLAY_NAMES: Record<BotCallbackChain, string> = {
  [BotCallbackChain.CHAIN_SOLANA]: 'Solana (SOL)',
  [BotCallbackChain.CHAIN_BASE]: 'Base (ETH)',
  [BotCallbackChain.CHAIN_TON]: 'TON (TON)',
};