export enum BotCallbackAction {
  ACTION_BUY_GAS = 'ACTION_BUY_GAS',
  ACTION_MY_ORDERS = 'ACTION_MY_ORDERS',
  ACTION_HELP = 'ACTION_HELP',
  ACTION_BACK = 'ACTION_BACK',
  ACTION_HOME = 'ACTION_HOME',
  ACTION_PAY_NOW = 'ACTION_PAY_NOW',
  ACTION_CANCEL_ORDER = 'ACTION_CANCEL_ORDER',
  ACTION_SELL_CRYPTO = 'ACTION_SELL_CRYPTO',
  ACTION_BANK = 'ACTION_BANK',
  ACTION_WALLET = 'ACTION_WALLET',
  ACTION_WITHDRAW = 'ACTION_WITHDRAW',
}

export enum BotCallbackChain {
  CHAIN_SOLANA = 'CHAIN_SOLANA',
  CHAIN_BASE = 'CHAIN_BASE',
  CHAIN_TON = 'CHAIN_TON',
  CHAIN_BSC = 'CHAIN_BSC',
  CHAIN_USDT = 'CHAIN_USDT',
  CHAIN_USDT_TON = 'CHAIN_USDT_TON',
  CHAIN_USDT_SOL = 'CHAIN_USDT_SOL',
  CHAIN_USDT_BSC = 'CHAIN_USDT_BSC',
  CHAIN_USDT_BASE = 'CHAIN_USDT_BASE',
}

export enum BotCallbackAmount {
  AMT_1000 = 'AMT_1000',
  AMT_2500 = 'AMT_2500',
  AMT_5000 = 'AMT_5000',
  AMT_CUSTOM = 'AMT_CUSTOM',
}

export enum BotCallbackQuantity {
  QTY_SOL_005 = 'QTY_SOL_005',
  QTY_SOL_01 = 'QTY_SOL_01',
  QTY_SOL_05 = 'QTY_SOL_05',
  QTY_SOL_1 = 'QTY_SOL_1',
  QTY_TON_1 = 'QTY_TON_1',
  QTY_TON_5 = 'QTY_TON_5',
  QTY_TON_10 = 'QTY_TON_10',
  QTY_TON_20 = 'QTY_TON_20',
  QTY_ETH_001 = 'QTY_ETH_001',
  QTY_ETH_005 = 'QTY_ETH_005',
  QTY_ETH_01 = 'QTY_ETH_01',
  QTY_USDT_5 = 'QTY_USDT_5',
  QTY_USDT_10 = 'QTY_USDT_10',
  QTY_USDT_25 = 'QTY_USDT_25',
  QTY_USDT_50 = 'QTY_USDT_50',
  QTY_CUSTOM = 'QTY_CUSTOM',
}

export enum BotCallbackCryptoAsset {
  CRYPTO_USDT = 'CRYPTO_USDT',
  // Temporarily disabled - USDT only for off-ramp
  // CRYPTO_TON = 'CRYPTO_TON',
  // CRYPTO_SOL = 'CRYPTO_SOL',
}

export enum BotCallbackPayoutDestination {
  PAYOUT_INTERNAL_WALLET = 'PAYOUT_INTERNAL_WALLET',
  PAYOUT_SAVED_BANK = 'PAYOUT_SAVED_BANK',
}

export enum BotCallbackBank {
  BANK_SELECT = 'BANK_SELECT',
}

export enum BotSessionStep {
  IDLE = 'IDLE',
  SELECT_CHAIN = 'SELECT_CHAIN',
  SELECT_AMOUNT = 'SELECT_AMOUNT',
  AWAITING_CUSTOM_AMOUNT = 'AWAITING_CUSTOM_AMOUNT',
  AWAITING_WALLET = 'AWAITING_WALLET',
  AWAITING_SELL_AMOUNT = 'AWAITING_SELL_AMOUNT',
  AWAITING_SELL_TX_ID = 'AWAITING_SELL_TX_ID',
  AWAITING_SELL_PAYOUT_CHOICE = 'AWAITING_SELL_PAYOUT_CHOICE',
  AWAITING_SELL_BANK_CHOICE = 'AWAITING_SELL_BANK_CHOICE',
  AWAITING_BANK_SELECTION = 'AWAITING_BANK_SELECTION',
  AWAITING_BANK_NAME_INPUT = 'AWAITING_BANK_NAME_INPUT',
  AWAITING_ACCOUNT_NUMBER = 'AWAITING_ACCOUNT_NUMBER',
  AWAITING_WITHDRAWAL_AMOUNT = 'AWAITING_WITHDRAWAL_AMOUNT',
  AWAITING_WITHDRAWAL_BANK = 'AWAITING_WITHDRAWAL_BANK',
  AWAITING_WITHDRAWAL_CONFIRMATION = 'AWAITING_WITHDRAWAL_CONFIRMATION',
  SELECT_TOKEN_QUANTITY = 'SELECT_TOKEN_QUANTITY',
  AWAITING_CUSTOM_QUANTITY = 'AWAITING_CUSTOM_QUANTITY',
}

export const AMOUNT_NAIRA_MAP: Partial<Record<BotCallbackAmount, number>> = {
  [BotCallbackAmount.AMT_1000]: 1000,
  [BotCallbackAmount.AMT_2500]: 2500,
  [BotCallbackAmount.AMT_5000]: 5000,
};

export const CHAIN_DISPLAY_NAMES: Record<BotCallbackChain, string> = {
  [BotCallbackChain.CHAIN_SOLANA]: 'Solana (SOL)',
  [BotCallbackChain.CHAIN_BASE]: 'Base (ETH)',
  [BotCallbackChain.CHAIN_TON]: 'TON (TON)',
  [BotCallbackChain.CHAIN_BSC]: 'BSC (BNB)',
  [BotCallbackChain.CHAIN_USDT]: 'USDT',
  [BotCallbackChain.CHAIN_USDT_TON]: 'USDT (TON)',
  [BotCallbackChain.CHAIN_USDT_SOL]: 'USDT (SOL)',
  [BotCallbackChain.CHAIN_USDT_BSC]: 'USDT (BSC)',
  [BotCallbackChain.CHAIN_USDT_BASE]: 'USDT (BASE)',
};